theme: jekyll-theme-minimal
# --- Serving options --- #
# If you are building a simple GitHub user page (username.github.io) then use these settings:
# url is the full website URL
url: "https://smcorwin.github.io/"
# baseurl is the website's URL without the hostname
baseurl: ""

# Name of website
title: Samuel Corwin
# Short description of your site
description: Renewable Energy Market and Policy Analyst

# --- Navigation bar options --- #
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/.jpg"

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Professional Experience: "professionalexperience"
  Personal: "personal"
  

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Samuel M. Corwin
  email: "samuelcorwin4@gmail.com"
  github: smcorwin
  linkedin: 

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  github: true
  linkedin: true
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer


# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA


# --- Don't need to touch anything below here (but you can if you want) --- #

